### ISSUE TITLE
Plugin template

### ISSUE THREAD

**Issue by deanshub** [deanshub/nissix-plugins#2]
Create a command that generates a template for a new plugin.

it should be in the npm scripts as `create`
it should allow the user to choose the name of the plugin (preferably in the command `create prettier`)
it should allow choosing a language (currently) 
1. `typescript` which will also generate `tsconfig.json` and some starter files
2. `other` which will generate just a `package.json` in the relevant directory

you should checkout [cmd-ts](https://www.npmjs.com/package/cmd-ts) and [generate-template-files](https://www.npmjs.com/package/generate-template-files)

**Comment by liorbentov** [comment]
@deanshub, Please assign this issue to me
